services:
- type: web
  name: flask-app
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -w 4 app:app
  envVars:
  - key: DATABASE_URI
    fromDatabase:
      name: nutshell
      property: connectionString
  - key: SECRET_KEY
    generateValue: true
  disk:
    name: flask-disk
    mountPath: /mnt
    sizeGB: 10
databases:
- name: nutshell
disks:
- name: flask-disk
  sizeGB: 10